export interface IntegrationApp {
  name: string;
  description: string;
  category: string;
  icon?: string;
}

export const INTEGRATION_CATEGORIES = [
  "All",
  "Marketing & Sales",
  "Development & DevOps",
  "Finance & Payments",
  "Productivity & Collaboration",
  "Data & Analytics",
  "Design & Content",
  "CRM & Support",
  "Cloud & Infrastructure",
  "Research & Science",
  "HR & Legal",
  "Travel & Events",
  "Communication",
] as const;

export const INTEGRATION_APPS: IntegrationApp[] = [
  { name: "10x Genomics Cloud", description: "Interact with 10x Genomics Cloud platform", category: "Research & Science" },
  { name: "ActiveCampaign", description: "Autonomous marketing to transform how you work", category: "Marketing & Sales" },
  { name: "Ahrefs", description: "SEO & AI search analytics", category: "Marketing & Sales" },
  { name: "Aiera", description: "Live events, filings, company publications, and more", category: "Data & Analytics" },
  { name: "AirOps", description: "Craft content that wins AI search", category: "Marketing & Sales" },
  { name: "Airtable", description: "Bring your structured data to Claude", category: "Productivity & Collaboration" },
  { name: "Airwallex", description: "Integrate with the Airwallex Platform", category: "Finance & Payments" },
  { name: "Aiwyn Tax", description: "Prepare your federal & state tax return 100% accurately", category: "Finance & Payments" },
  { name: "Amplitude", description: "Give your teams powerful behavioral insights", category: "Data & Analytics" },
  { name: "Apollo.io", description: "Find buyers. Book more meetings. Close more deals.", category: "Marketing & Sales" },
  { name: "Asana", description: "Connect to Asana to coordinate tasks, projects, and goals", category: "Productivity & Collaboration" },
  { name: "Atlassian Rovo", description: "Access Jira & Confluence from Claude", category: "Development & DevOps" },
  { name: "Attio", description: "Search, manage, and update your Attio CRM", category: "CRM & Support" },
  { name: "Aura", description: "Company intelligence & workforce analytics", category: "Data & Analytics" },
  { name: "AWS Marketplace", description: "Discover, evaluate, and buy solutions for the cloud", category: "Cloud & Infrastructure" },
  { name: "Base44", description: "Build and manage Base44 apps", category: "Development & DevOps" },
  { name: "Benchling", description: "Connect to R&D data, source experiments, and notebooks", category: "Research & Science" },
  { name: "Benevity", description: "Find and engage with verified nonprofits", category: "HR & Legal" },
  { name: "Bigdata.com", description: "Access real-time financial data", category: "Finance & Payments" },
  { name: "BioRender", description: "Search for and use scientific templates and icons", category: "Research & Science" },
  { name: "bioRxiv", description: "Access to bioRxiv and medRxiv preprint data", category: "Research & Science" },
  { name: "Bitly", description: "Shorten links, generate QR Codes, and track performance", category: "Marketing & Sales" },
  { name: "Blackbaud", description: "Search, explore, and query Blackbaud data", category: "Data & Analytics" },
  { name: "Blockscout", description: "Access and analyze blockchain data", category: "Data & Analytics" },
  { name: "Box", description: "Search, access and get insights on your Box content", category: "Productivity & Collaboration" },
  { name: "Braze", description: "Analyze trends and gather insights on Campaigns", category: "Marketing & Sales" },
  { name: "Brex", description: "Intelligent finance automation", category: "Finance & Payments" },
  { name: "Calendly", description: "Manage event types, availability, and bookings", category: "Productivity & Collaboration" },
  { name: "Campfire", description: "Search, analyze, and export Campfire data", category: "Data & Analytics" },
  { name: "Candid", description: "Research nonprofits and funders using Candid's data", category: "Research & Science" },
  { name: "Canva", description: "Search, create, autofill, and export Canva designs", category: "Design & Content" },
  { name: "CB Insights", description: "Predictive intelligence on private companies", category: "Data & Analytics" },
  { name: "CData", description: "Managed MCP platform for 350 sources", category: "Data & Analytics" },
  { name: "ChEMBL", description: "Access to the ChEMBL Database", category: "Research & Science" },
  { name: "Chronograph", description: "Interact with your Chronograph data directly", category: "Finance & Payments" },
  { name: "Circleback", description: "Search and access context from meetings", category: "Productivity & Collaboration" },
  { name: "Clarify", description: "Query your CRM. Create records. Ask anything.", category: "CRM & Support" },
  { name: "Clarity AI", description: "Simulate fund classifications under proposed SFDR 2.0", category: "Finance & Payments" },
  { name: "Clay", description: "Find prospects. Research accounts. Personalize outreach", category: "Marketing & Sales" },
  { name: "Clerk", description: "Add authentication, organizations, and billing", category: "Development & DevOps" },
  { name: "ClickUp", description: "Project management & collaboration for teams & agents", category: "Productivity & Collaboration" },
  { name: "Clinical Trials", description: "Access ClinicalTrials.gov data", category: "Research & Science" },
  { name: "Clockwise", description: "Advanced scheduling and time management for work", category: "Productivity & Collaboration" },
  { name: "Close", description: "Securely connect to your Close data", category: "CRM & Support" },
  { name: "Cloudflare", description: "Build applications with compute, storage, and AI", category: "Cloud & Infrastructure" },
  { name: "Cloudinary", description: "Manage, transform and deliver your images & videos", category: "Design & Content" },
  { name: "CMS Coverage", description: "Access the CMS Coverage Database", category: "Research & Science" },
  { name: "Common Room", description: "Your GTM Copilot", category: "Marketing & Sales" },
  { name: "Consensus", description: "Explore scientific research", category: "Research & Science" },
  { name: "Context7", description: "Up-to-date docs for LLMs and AI code editors", category: "Development & DevOps" },
  { name: "Cortellis", description: "Trusted Regulatory Answers, by Clarivate Cortellis", category: "Research & Science" },
  { name: "Coupler.io", description: "Access business data from hundreds of sources", category: "Data & Analytics" },
  { name: "Craft", description: "Notes & second brain", category: "Productivity & Collaboration" },
  { name: "Crossbeam", description: "Explore partner data and ecosystem insights", category: "Marketing & Sales" },
  { name: "Crypto.com", description: "Real time prices, orders, charts for crypto", category: "Finance & Payments" },
  { name: "Customer.io", description: "Explore customer data and generate insights", category: "Marketing & Sales" },
  { name: "Daloopa", description: "Financial fundamental data and KPIs with hyperlinks", category: "Finance & Payments" },
  { name: "Databricks", description: "Managed MCP servers with Unity Catalog and Mosaic AI", category: "Data & Analytics" },
  { name: "DataGrail", description: "Secure AI orchestration for privacy", category: "HR & Legal" },
  { name: "Day AI", description: "Know everything about your prospects & customers", category: "CRM & Support" },
  { name: "DevRev", description: "Search and update your company's knowledge graph", category: "Development & DevOps" },
  { name: "Dice", description: "Find active tech jobs on Dice", category: "HR & Legal" },
  { name: "DirectBooker", description: "Compare hotels, then book direct", category: "Travel & Events" },
  { name: "DocuSeal", description: "Sign, send & manage documents with DocuSeal", category: "HR & Legal" },
  { name: "Docusign", description: "Intelligent, secure contract management", category: "HR & Legal" },
  { name: "Dremio Cloud", description: "Analyze and get insights from your lakehouse data", category: "Data & Analytics" },
  { name: "Egnyte", description: "Securely access and analyze Egnyte content", category: "Productivity & Collaboration" },
  { name: "Excalidraw", description: "Creating interactive hand-drawn diagrams", category: "Design & Content" },
  { name: "FactSet", description: "Access institutional-quality financial data and analytics", category: "Finance & Payments" },
  { name: "Fellow.ai", description: "Chat with your meetings to uncover actionable insights", category: "Productivity & Collaboration" },
  { name: "Fever", description: "Discover live entertainment events worldwide", category: "Travel & Events" },
  { name: "Figma", description: "Generate diagrams and better code from Figma context", category: "Design & Content" },
  { name: "Fireflies", description: "Analyze and generate insights from meeting transcripts", category: "Productivity & Collaboration" },
  { name: "G2", description: "Bring real buyer signals into AI workflows", category: "Marketing & Sales" },
  { name: "Gainsight", description: "Power AI Workflows with Customer Context", category: "CRM & Support" },
  { name: "Gamma", description: "Create presentations, docs, socials, and sites with AI", category: "Design & Content" },
  { name: "Glean", description: "Bring enterprise context to your AI tools", category: "Productivity & Collaboration" },
  { name: "Gmail", description: "Search your emails, surface insights, and draft replies", category: "Communication" },
  { name: "GoDaddy", description: "Search domains and check availability", category: "Cloud & Infrastructure" },
  { name: "Google Calendar", description: "Schedule meetings based on availability", category: "Productivity & Collaboration" },
  { name: "Google Cloud BigQuery", description: "BigQuery: Advanced analytical insights for agents", category: "Data & Analytics" },
  { name: "Google Compute Engine", description: "MCP server for Google Compute Engine", category: "Cloud & Infrastructure" },
  { name: "Google Drive", description: "Search and read your Docs, Sheets, and Slides", category: "Productivity & Collaboration" },
  { name: "Granola", description: "The AI notepad for meetings", category: "Productivity & Collaboration" },
  { name: "Granted", description: "Discover every grant opportunity in existence", category: "Finance & Payments" },
  { name: "GraphOS", description: "Search Apollo docs, specs, and best practices", category: "Development & DevOps" },
  { name: "Guru", description: "Search and interact with your company knowledge", category: "Productivity & Collaboration" },
  { name: "Gusto", description: "Query and analyze your Gusto data", category: "HR & Legal" },
  { name: "Harmonic", description: "Discover, research, and enrich companies and people", category: "Marketing & Sales" },
  { name: "Harvey", description: "Answer legal queries, search vaults, and research", category: "HR & Legal" },
  { name: "Hex", description: "Answer questions with the Hex agent", category: "Data & Analytics" },
  { name: "Honeycomb", description: "Query and explore observability data and SLOs", category: "Development & DevOps" },
  { name: "HubSpot", description: "Chat with your CRM data to get personalized insights", category: "CRM & Support" },
  { name: "Hugging Face", description: "Access the HF Hub and thousands of Gradio Apps", category: "Development & DevOps" },
  { name: "Indeed", description: "Search for jobs on Indeed", category: "HR & Legal" },
  { name: "Intapp Celeste", description: "Securely access Intapp Celeste products", category: "HR & Legal" },
  { name: "Intercom", description: "AI access to Intercom data for better customer insights", category: "CRM & Support" },
  { name: "Intuit QuickBooks", description: "Business Finances made simple", category: "Finance & Payments" },
  { name: "Intuit TurboTax", description: "Estimate tax refunds and connect with live tax experts", category: "Finance & Payments" },
  { name: "Jam", description: "Record screen and collect automatic context for issues", category: "Development & DevOps" },
  { name: "Jentic", description: "One connection to access all your tools securely", category: "Development & DevOps" },
  { name: "Jotform", description: "Create forms & analyze submissions", category: "Productivity & Collaboration" },
  { name: "Kiwi.com", description: "Search flights in Claude", category: "Travel & Events" },
  { name: "Klaviyo", description: "Report, strategize & create with real-time data", category: "Marketing & Sales" },
  { name: "Krisp", description: "Add your meetings context via transcripts and notes", category: "Productivity & Collaboration" },
  { name: "lastminute.com", description: "Search, compare and book flights and hotels", category: "Travel & Events" },
  { name: "LegalZoom", description: "Attorney guidance & tools for business & personal needs", category: "HR & Legal" },
  { name: "LILT", description: "High-quality translation with human verification", category: "Design & Content" },
  { name: "Linear", description: "Manage issues, projects & team workflows", category: "Development & DevOps" },
  { name: "Local Falcon", description: "AI visibility and local search intelligence platform", category: "Marketing & Sales" },
  { name: "LSEG", description: "Access best in class data & analytics", category: "Finance & Payments" },
  { name: "Lumin", description: "Manage documents, send signature requests, convert PDF", category: "Productivity & Collaboration" },
  { name: "LunarCrush", description: "Add real-time social media data to your searches", category: "Data & Analytics" },
  { name: "Magic Patterns", description: "Discuss and iterate on Magic Patterns designs", category: "Design & Content" },
  { name: "MailerLite", description: "Turn into your email marketing assistant", category: "Marketing & Sales" },
  { name: "Make", description: "Run Make scenarios and manage your Make account", category: "Productivity & Collaboration" },
  { name: "Medidata", description: "Medidata provides clinical trial software solutions", category: "Research & Science" },
  { name: "Mem", description: "The AI notebook for everything on your mind", category: "Productivity & Collaboration" },
  { name: "Mercury", description: "Search, analyze and understand your finances", category: "Finance & Payments" },
  { name: "Mermaid Chart", description: "Validates syntax, renders diagrams as high-quality SVG", category: "Design & Content" },
  { name: "Metaview", description: "The AI platform for recruiting", category: "HR & Legal" },
  { name: "Microsoft 365", description: "Access SharePoint, OneDrive, Outlook, and Teams", category: "Productivity & Collaboration" },
  { name: "Microsoft Learn", description: "Search trusted Microsoft docs", category: "Development & DevOps" },
  { name: "Midpage", description: "Conduct legal research and create work product", category: "HR & Legal" },
  { name: "Miro", description: "Access and create new content on Miro boards", category: "Design & Content" },
  { name: "Mixpanel", description: "Analyze, query, and manage your Mixpanel data", category: "Data & Analytics" },
  { name: "Monday", description: "Manage projects, boards, and workflows", category: "Productivity & Collaboration" },
  { name: "Moody's Analytics", description: "Risk insights, analytics, and decision intelligence", category: "Finance & Payments" },
  { name: "Morningstar", description: "Up-to-date investment and market insights", category: "Finance & Payments" },
  { name: "MotherDuck", description: "Get answers from your data", category: "Data & Analytics" },
  { name: "MSCI", description: "Turn data into insight", category: "Finance & Payments" },
  { name: "MT Newswires", description: "Trusted real-time global financial news provider", category: "Data & Analytics" },
  { name: "n8n", description: "Access and run your n8n workflows", category: "Productivity & Collaboration" },
  { name: "Netlify", description: "Create, deploy, manage, and secure websites", category: "Cloud & Infrastructure" },
  { name: "Notion", description: "Connect your Notion workspace to search and update", category: "Productivity & Collaboration" },
  { name: "Omni Analytics", description: "Query your data using natural language", category: "Data & Analytics" },
  { name: "Open Targets", description: "Drug target discovery and prioritisation platform", category: "Research & Science" },
  { name: "Oracle NetSuite", description: "Connect to NetSuite data for analysis & insights", category: "Finance & Payments" },
  { name: "Outreach", description: "Unleash your team's best performance", category: "Marketing & Sales" },
  { name: "Owkin", description: "Interact with AI agents built for biology", category: "Research & Science" },
  { name: "PagerDuty", description: "Manage incidents, services and on-call schedules", category: "Development & DevOps" },
  { name: "PayPal", description: "Access PayPal payments platform", category: "Finance & Payments" },
  { name: "Pendo", description: "Connect to Pendo for product and user insights", category: "Data & Analytics" },
  { name: "Pigment", description: "Analyze business data", category: "Data & Analytics" },
  { name: "PitchBook", description: "PitchBook data, embedded in the way you work", category: "Finance & Payments" },
  { name: "Plaid", description: "Monitor, debug, and optimize your Plaid integration", category: "Finance & Payments" },
  { name: "PlanetScale", description: "Authenticated access to your Postgres and MySQL DBs", category: "Development & DevOps" },
  { name: "Port IO", description: "Build and query your developer portal", category: "Development & DevOps" },
  { name: "PostHog", description: "Query, analyze, and manage your PostHog insights", category: "Data & Analytics" },
  { name: "Postman", description: "Give API context to your coding agents", category: "Development & DevOps" },
  { name: "Process Street", description: "Explore and update your Process Street data", category: "Productivity & Collaboration" },
  { name: "PubMed", description: "Search biomedical literature from PubMed", category: "Research & Science" },
  { name: "Pylon", description: "Search and manage Pylon support issues", category: "CRM & Support" },
  { name: "Qlik", description: "Analyze, integrate, and take action on your data", category: "Data & Analytics" },
  { name: "Quartr", description: "Financial data and AI infrastructure for company research", category: "Finance & Payments" },
  { name: "Ramp", description: "Search, access, and analyze your Ramp financial data", category: "Finance & Payments" },
  { name: "Razorpay", description: "Turn into your Razorpay Dashboard Assistant", category: "Finance & Payments" },
  { name: "Sanity", description: "Create, query, and manage structured content", category: "Design & Content" },
  { name: "Sentry", description: "Search, query, and debug errors intelligently", category: "Development & DevOps" },
  { name: "SignNow", description: "Automate eSignature workflows", category: "HR & Legal" },
  { name: "Similarweb", description: "Real time web, mobile app, and market data", category: "Data & Analytics" },
  { name: "Slack", description: "Send messages, create canvases, and fetch Slack data", category: "Communication" },
  { name: "Smartsheet", description: "Analyze and manage Smartsheet data", category: "Productivity & Collaboration" },
  { name: "Snowflake", description: "Retrieve both structured and unstructured data", category: "Data & Analytics" },
  { name: "S&P Global", description: "Query a range of S&P Global datasets", category: "Finance & Payments" },
  { name: "Square", description: "Search and manage transaction and payment data", category: "Finance & Payments" },
  { name: "Starburst", description: "Securely retrieve data from your federated data sources", category: "Data & Analytics" },
  { name: "Stripe", description: "Payment processing and financial infrastructure tools", category: "Finance & Payments" },
  { name: "Supabase", description: "Manage databases, authentication, and storage", category: "Development & DevOps" },
  { name: "Supermetrics", description: "Analyze marketing performance across 200+ platforms", category: "Marketing & Sales" },
  { name: "Tavily", description: "Connect your AI agents to the web", category: "Development & DevOps" },
  { name: "Ticket Tailor", description: "Event platform for managing tickets, orders & more", category: "Travel & Events" },
  { name: "Trivago", description: "Find your ideal hotel at the best price", category: "Travel & Events" },
  { name: "Twilio", description: "Cloud communications platform for SMS, voice", category: "Communication" },
  { name: "Udemy Business", description: "Search and explore skill-building resources", category: "HR & Legal" },
  { name: "Vercel", description: "Analyze, debug, and manage projects and deployments", category: "Cloud & Infrastructure" },
  { name: "Visier", description: "Find people, productivity and business impact insights", category: "HR & Legal" },
  { name: "Webflow", description: "Design pages, manage CMS content, and automate tasks", category: "Design & Content" },
  { name: "Windsor.ai", description: "Connect 325+ marketing, analytics and CRM data sources", category: "Data & Analytics" },
  { name: "Wix", description: "Manage and build sites and apps on Wix", category: "Design & Content" },
  { name: "WordPress.com", description: "Secure AI access to manage your WordPress.com sites", category: "Design & Content" },
  { name: "Workato", description: "Automate workflows and connect your business apps", category: "Productivity & Collaboration" },
  { name: "Wyndham Hotels", description: "Discover the right Wyndham Hotel for you, faster", category: "Travel & Events" },
  { name: "Zapier", description: "Automate workflows across thousands of apps", category: "Productivity & Collaboration" },
  { name: "Zoho Books", description: "Zoho Books MCP for Smart Finance Ops", category: "Finance & Payments" },
  { name: "Zoho CRM", description: "MCP Server for Zoho CRM Workflows", category: "CRM & Support" },
  { name: "Zoho Projects", description: "Zoho Projects MCP for Task & Project Automation", category: "Productivity & Collaboration" },
  { name: "ZoomInfo", description: "Enrich contacts & accounts with GTM intelligence", category: "Marketing & Sales" },
  { name: "Resend", description: "Email API for developers", category: "Communication" },
  { name: "Telegram", description: "Messaging platform with Bot API", category: "Communication" },
  { name: "AWS S3", description: "Read and write data files in AWS S3 buckets", category: "Cloud & Infrastructure" },
  { name: "Firecrawl", description: "AI-powered scraper, search and retrieval tool", category: "Development & DevOps" },
  { name: "Contentful", description: "Headless CMS for content delivery", category: "Design & Content" },
  { name: "ElevenLabs", description: "AI voice generation, text-to-speech", category: "Design & Content" },
  { name: "Perplexity", description: "AI-powered search and answer engine", category: "Development & DevOps" },
  { name: "Twitch", description: "Live streaming platform for gaming and creative content", category: "Design & Content" },
];
